name: demo-backend

on:
  push:
    branches: [master]

env:
  REGISTRY: roxsross12
  IMAGE_NAME: backend-bootcamp


jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }} 
                  
      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
      
      # test the apps     
      - name: test
        run: |
          npm run test   

 
